FROM php:7.4-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
&& docker-php-ext-install pdo_mysql \
&& docker-php-source delete \
&& rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html/

COPY entrypoint-php-script /usr/local/bin/
ENTRYPOINT ["bash", "entrypoint-php-script"]


#CMD git clone https://github.com/symfony/website-skeleton.git /var/www/html && composer install && apache2-foreground

