#!/bin/sh
GITDEPOT="https://github.com/ljr95/docker-git.git"
DIR="/var/www/html"

eval "$(ssh-agent -s)"
if [ ! -d "/root/.ssh/" ]; then
    ssh-add -k /run/secrets/id_rsa
    mkdir /root/.ssh
    ssh-keyscan github.com > /root/.ssh/known_hosts
    # now execute command which require authentication via ssh (example, git clone from a private repo)
fi

# look for empty dir 
if [ "$(ls -A $DIR)" ]; then
	echo "$DIR is not empty"

	if [ "$(ls -A $DIR/.git)" ]; then
		echo "Upgrade projet"
		git fetch --all
		git pull
		composer install		
	else
		echo "There is no git folder"
	fi

else
    echo "$DIR est vide, initialisation du projet"
    git clone $GITDEPOT /var/www/html/
    composer install
fi

exec apache2-foreground
